---
- name: Playbook que habilita a aplicação web
  tasks:
    - name: Instala o apache
      ansible.builtin.yum:
        name: httpd
        state: present
    
    - name: Habilita ele na inicialização
      systemd:
        name: httpd
        state: started
        enabled: True
        masked: False

    - name: Copia o index.html para o servidor
      ansible.builtin.copy:
        content: '<html><body>Aplicação do Roger</body></html>'
        dest: /var/www/html/index.htm
        owner: root
        group: root
        mode: '0644'