---
- name: Playbook que habilita a aplicação web
  hosts: clienterhel7.transp.com
  tasks:
    - name: Instala o apache
      ansible.builtin.yum:
        name: httpd
        state: present
    
    - name: Habilita ele na inicialização
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: True
        masked: False

    - name: Copia o index.html para o servidor
      ansible.builtin.copy:
        content: '<html><body>Aplicação do Roger</body></html>'
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Libera a porta 80 no firewall
      ansible.builtin.firewalld:
        permanent: True
        state: enabled
        service: http
        immediate: True

    - name: Testa a conexão
      ansible.builtin.uri:
        url: http://clienterhel7.transp.com/index.html
        method: GET
        status_code: 200