---
- name: Playbook que brinca com API de mentirinha
  hosts: clienterhel8.transp.com
  become: True
  tasks:
    - name: cat no arquivo
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', '/root/saida_api.txt') }}"
    - name: Teste
      ansible.builtin.shell: uname -n; ls /root
        
      