---
- name: Playbook que brinca com API de mentirinha
  hosts: clienterhel8.transp.com
  become: True
  tasks:
    - name: cat no arquivo
      ansible.builtin.shell: cat /root/saida_api.txt
      register: saida_api

    - name: Exibe saída
      debug:
        msg: "{{ saida_api.stdout }}"

    - name: Exibe apenas uma parte
      debug:
        msg: "{{ item['id'] }}"
      loop: "{{ (saida_api.stdout | from_json)['resources'] }}"
        
      