---
- name: teste
  hosts: localhost
  tasks:
    - name: teste
      vars:
        hosts_var:
          - name: bastion
            ip:
              - 172.25.250.254
              - 172.25.252.1
        hosts_json: '[{"name": "bastion", "ip": ["172.25.250.254", "172.25.252.1"]}]'
      debug:
        msg: "Olha um JSON aí: {{ hosts_var | to_json }}"
    
    - name: Outro teste
      debug:
        msg: "{{ query('lines', 'ls /etc') }}"
