---
- name: Playbook que seta o satellite do jeito que eu quero (via API)
  hosts: localhost
  tasks:
    - name: Cria a host collection
      ansible.builtin.uri:
        url: https://satellite.transp.com/katello/api/host_collections
        method: POST
        body_format: json
        user: "admin"
        password: "redhat"
        force_basic_auth: True
        body:
          name: "redhat7"
          organization_id: 1


#    - name: Cria o ContentView

#    - name: Cria a activation-key