---
- name: Playbook que seta o satellite do jeito que eu quero (via API)
  hosts: localhost
  tasks:
    - name: Cria a host collection
      ansible.builtin.uri:
        url: https://satellite.transp.com/katello/api/host_collections
        method: POST
        body_format: json
        user: "admin"
        password: "redhat"
        force_basic_auth: True
        status_code: 201
        body:
          name: "redhat7"
          organization_id: 1
      when: False

    - name: Cria o ContentView
      ansible.builtin.uri:
        url: /katello/api/organizations/1/content_views
        method: POST
        body_format: json
        user: "admin"
        password: "redhat"
        force_basic_auth: True
        status_code: 201
        body:
          name: "base7"
          label: "base7"
          composite: False
          solve_dependencies: False
          organization_id: 1


#    - name: Cria a activation-key